### ISSUE TITLE
Não consigo implementar o <p:fileUpload>

### ISSUE THREAD

**Issue by viniciussoaresti** [ifpe-cti/pmgus#101]
01-Dec-2018 22:56:49.253 WARNING [http-nio-8084-exec-15] com.sun.faces.context.SessionMap.put JSF1063: WARNING! Setting non-serializable attribute value into HttpSession (key: fachada, value class: com.github.viniciussoaresti.pmgus.controladores.Fachada).
org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file input stream from file: 'teste.xlsx'
	at org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:164)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:151)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:272)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:181)
	at com.github.viniciussoaresti.pmgus.controladores.ExcelController.cadastrarArmas(ExcelController.java:51)
	at com.github.viniciussoaresti.pmgus.controladores.Fachada.cadastrarArmaExcel(Fachada.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:89)
	at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:90)
	at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:106)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:95)
	at javax.faces.component.UICommand.broadcast(UICommand.java:246)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:871)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1419)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: teste.xlsx (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:161)
	... 47 more
01-Dec-2018 22:56:49.897 1100 [http-nio-8084-exec-14] com.sun.faces.context.ExceptionHandlerImpl.log JSF1073: java.lang.NoClassDefFoundError caught during processing of RENDER_RESPONSE 6 : UIComponent-ClientId=, Message=javax/servlet/jsp/jstl/core/Config
01-Dec-2018 22:56:49.898 1100 [http-nio-8084-exec-14] com.sun.faces.context.ExceptionHandlerImpl.log javax/servlet/jsp/jstl/core/Config
 java.lang.NoClassDefFoundError: javax/servlet/jsp/jstl/core/Config
	at com.sun.faces.application.view.JspViewHandlingStrategy.executePageToBuildView(JspViewHandlingStrategy.java:361)
	at com.sun.faces.application.view.JspViewHandlingStrategy.buildView(JspViewHandlingStrategy.java:130)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:732)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

01-Dec-2018 22:56:49.913 1100 [http-nio-8084-exec-22] com.sun.faces.context.ExceptionHandlerImpl.log JSF1073: java.lang.NoClassDefFoundError caught during processing of RENDER_RESPONSE 6 : UIComponent-ClientId=, Message=javax/servlet/jsp/jstl/core/Config
01-Dec-2018 22:56:49.913 1100 [http-nio-8084-exec-22] com.sun.faces.context.ExceptionHandlerImpl.log javax/servlet/jsp/jstl/core/Config
 java.lang.NoClassDefFoundError: javax/servlet/jsp/jstl/core/Config
	at com.sun.faces.application.view.JspViewHandlingStrategy.executePageToBuildView(JspViewHandlingStrategy.java:361)
	at com.sun.faces.application.view.JspViewHandlingStrategy.buildView(JspViewHandlingStrategy.java:130)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:732)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Classes e página web:
https://github.com/viniciussoaresti/pmgus/blob/fachada/src/main/webapp/cadastroExcel.xhtml
https://github.com/viniciussoaresti/pmgus/blob/fachada/src/main/java/com/github/viniciussoaresti/pmgus/controladores/ExcelController.java
https://github.com/viniciussoaresti/pmgus/blob/fachada/src/main/java/com/github/viniciussoaresti/pmgus/controladores/Fachada.java

Por favor ajudem @lsoaresesilva @fabriciofx @vsnepomuceno @davidalain só falta isso pro meu excel pegar ;-;

**Comment by fabriciofx** [comment]
@viniciussoaresti Procure olhar os `Caused by`: `Caused by: java.io.FileNotFoundException: teste.xlsx (The system cannot find the file specified)`, pelo que este erro indica, ele não está conseguindo localizar o arquivo `teste.xlsx`. Como você está passando a localização deste arquivo?

**Comment by viniciussoaresti** [comment]
@fabriciofx 

A página web:
<h:form enctype="multipart/form-data">
            <p:fileUpload value="#{fachada.excelcontroller.arquivoupload}" mode="simple" skinSimple="true" fileUploadListener="#{fachada.excelcontroller.carregarUpload}"/>
            <br/><br/>
            
            <p:commandButton value="Cadastrar Armas" ajax="false" action="#{fachada.cadastrarArmaExcel()}"/>
</h:form>

Código Java:
List<Arma> armas;
    private UploadedFile arquivoupload;

    public UploadedFile getArquivoupload() {
        return arquivoupload;
    }

    public void setArquivoupload(UploadedFile arquivoupload) {
        this.arquivoupload = arquivoupload;
    }

    public void carregarUpload(FileUploadEvent event) throws FileNotFoundException, IOException {
        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO, "Sucesso!", "O upload foi realizado!"));
        setArquivoupload(event.getFile());
    }

    public void cadastrarArmas(ArmaController armacontroller) {
        try {
            armas = new ArrayList<>();
            if (arquivoupload != null) {
                OPCPackage pkg = OPCPackage.open(new File(arquivoupload.getFileName()));

**Comment by viniciussoaresti** [comment]
@fabriciofx 
Eu tava dando uma olhada em vários foruns (to nisso faz uns 3-5 dias) e eles falam mt de configurar o web.xml, baixar umas dependencias, configurar coisa no classpath e afins, e nada funciona, e não consigo achar exemplos na web pra tentar implementar ;-;
(Aliás aquele showcase do primefaces viu...)

**Comment by fabriciofx** [comment]
@viniciussoaresti Vá por partes:

1. Dê uma lida aqui: http://blog.triadworks.com.br/upload-de-arquivos-com-jsf-2-2
2. Tente implementar o upload de um arquivo simples qualquer;
3. Tente fazer o upload de um arquivo do Excel;
4. Passe o arquivo uploaded para este framework que trabalha com arquivos do Excel

**Comment by MatheusDias18** [comment]
Implementei mas está dando NullPointerException no método importa. @fabriciofx @viniciussoaresti

**Comment by fabriciofx** [comment]
@MatheusDias18 Olhou o link que eu apontei? Implementou da forma que é explicado lá? Se sim, está dando `NullPointerException`? Pode colar o log de erro aqui?

**Comment by MatheusDias18** [comment]
implementei sim, do mesmo jeitinho. 

Caused by: javax.faces.el.EvaluationException: java.lang.NullPointerException
	at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:100)
	at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:106)
	... 36 more
Caused by: java.lang.NullPointerException
	at com.github.viniciussoaresti.pmgus.controladores.ExcelController.importa(ExcelController.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:89)
	at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:90)
	... 37 more


@fabriciofx

**Comment by MatheusDias18** [comment]
Agora deu este erro: 

 the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is application/x-www-form-urlencoded


como disse defini esse "multipart/form-data" no form do jeito que falava o tutorial @fabriciofx

**Comment by MatheusDias18** [comment]
Método de importação:

public void importa() {
        try {
            String conteudo = new Scanner(arquivo.getInputStream())
                .useDelimiter("\\A").next();
           
        } catch (IOException e) {
            // trata o erro
        }
     
    }

**Comment by fabriciofx** [comment]
@MatheusDias18 Você está:

1. Usando o JSF 2.2?
2. Deeclararando a nova namespace para a tag html: http://xmlns.jcp.org/jsf/html
3. Está usando as libraries com suporte a Servlet 3.0?

Além disso:
```
String conteudo = new Scanner(arquivo.getInputStream()).useDelimiter("\A").next();
```
ao meu ver, seria para algum arquivo no formato texto. Para salvar como arquivo, tente algo assim:
```
private Part file; // +getter+setter

public void save() {
    try (InputStream input = file.getInputStream()) {
        Files.copy(input, new File(uploads, filename).toPath());
    }
    catch (IOException e) {
        // Show faces message?
    }
}
```
Maiores informações: https://stackoverflow.com/questions/27677397/how-to-upload-file-using-jsf-2-2-hinputfile-where-is-the-saved-file

**Comment by MatheusDias18** [comment]
os 3 primeiros já estão certos!

**Comment by fabriciofx** [comment]
@MatheusDias18 Veja o resto...

**Comment by MatheusDias18** [comment]
@fabriciofx  Fiz tudo o que tinha no tutorial, mas continua null pointer exception.

**Comment by fabriciofx** [comment]
@MatheusDias18 Você tem que investigar *quem* está disparando o `NullPointerException`. É `file.getInputStream()`? Se sim, significa que não está funcionando o envio. Olhe também os logs do servidor web para ver se acha algo...

**Comment by viniciussoaresti** [comment]
@fabriciofx trocamos pro file do java mesmo, e tá dando certo. O importante é funcionar. Issue fechada, muito obrigado mesmo pela ajuda.

**Comment by fabriciofx** [comment]
@viniciussoaresti Como assim? Qual o commit que fechou essa issue? É bom mostrar pra aprender com o problema e saber a solução!
